config/routes.rb
Treehouz::Application.routes.draw do
  get 'scrapes/run' => 'scrapes#run'
  match 'auth/:provider/callback', to: 'sessions#create', via: [:get, :post]
  match 'auth/failure', to: redirect('/'), via: [:get, :post]
  match 'signout', to: 'sessions#destroy', as: 'signout', via: [:get, :post]
  resources :demos

  root 'dashboard#index'

end

app/models/demo.rb
class Demo < ActiveRecord::Base
end

app/models/scrape.rb
class Scrape < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  def self.from_omniauth(auth)
    where(auth.slice(:provider, :uid)).first_or_initialize.tap do |user|
      user.provider = auth.provider
      user.uid = auth.uid
      user.name = auth.info.name
      user.oauth_token = auth.credentials.token
      user.oauth_expires_at = Time.at(auth.credentials.expires_at)
      user.save!
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  private
  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
  helper_method :current_user
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  def index
  end
end

app/controllers/demos_controller.rb
class DemosController < ApplicationController
  before_action :set_demo, only: [:show, :edit, :update, :destroy]

  # GET /demos
  # GET /demos.json
  def index
    @demos = Demo.all
  end

  # GET /demos/1
  # GET /demos/1.json
  def show
  end

  # GET /demos/new
  def new
    @demo = Demo.new
  end

  # GET /demos/1/edit
  def edit
  end

  # POST /demos
  # POST /demos.json
  def create
    @demo = Demo.new(demo_params)

    respond_to do |format|
      if @demo.save
        format.html { redirect_to @demo, notice: 'Demo was successfully created.' }
        format.json { render action: 'show', status: :created, location: @demo }
      else
        format.html { render action: 'new' }
        format.json { render json: @demo.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /demos/1
  # PATCH/PUT /demos/1.json
  def update
    respond_to do |format|
      if @demo.update(demo_params)
        format.html { redirect_to @demo, notice: 'Demo was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @demo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /demos/1
  # DELETE /demos/1.json
  def destroy
    @demo.destroy
    respond_to do |format|
      format.html { redirect_to demos_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_demo
      @demo = Demo.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def demo_params
      params[:demo]
    end
end

app/controllers/scrapes_controller.rb
class ScrapesController < ApplicationController
    





  def init
        @vendor = "me"
        @graph = Koala::Facebook::API.new(current_user.oauth_token)
  end

  def run
    init
      def demorun
        p current_user.oauth_token
        @pull = @graph.get_connections(@vendor, "posts")
        p @result = @pull.first
        
        p @demo = Demo.new
        p @demo.handle = @vendor
        p @demo.fb_id = @result["id"]
        p @demo.message = @result["message"]
        p @demo.picture = @result["picture"]
        p @demo.link = @result["link"]
        p @demo.created = @result["created_time"]
        p @demo.updated = @result["updated_time"]
        # p @demo.shares = @result["shares"]["count"]
        # p @demo.likes = @graph.get_object("likes?limit=1000&id=#{@id}").size
        p @demo.save
      end
      (1..20).each do |i|
       demorun
    end
  end


  
end

  



  def run3
        @vendor = "lululemon"
        @graph = Koala::Facebook::API.new(current_user.oauth_token)
       def stress
          @demo = @graph.get_connections(@vendor, "posts")
          @demo = demo.new
          @demo.handle = @vendor
          @demo.content = @demo.to_s
          @demo.save
        end
    
    (1..100).each do |i|
      stress
    end

  end

  def run2
      @graph = Koala::Facebook::API.new(current_user.oauth_token)
      @demo = @graph.get_connections("lululemon", "posts")
      @demo = demo.new
      @demo.handle = "Petar"
      @demo.content = @demo.to_s
      @demo.save
  end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    user = User.from_omniauth(env["omniauth.auth"])
    session[:user_id] = user.id
    redirect_to root_url
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_url
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/demos_helper.rb
module DemosHelper
end

app/helpers/scrapes_helper.rb
module ScrapesHelper
end

app/views/dashboard/index.html.erb
<h1>Dashboard#index</h1>
<div id="user-widget">
  <% if current_user %>
    Welcome <strong><%= current_user.name %></strong>!
    <%= link_to "Sign out", signout_path, id: "sign_out" %>
  <% else %>
    <%= link_to "Sign in with Facebook", "/auth/facebook", id: "sign_in" %>
  <% end %>
</div>

app/views/demos/_form.html.erb
<%= form_for(@demo) do |f| %>
  <% if @demo.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@demo.errors.count, "error") %> prohibited this demo from being saved:</h2>

      <ul>
      <% @demo.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/demos/edit.html.erb
<h1>Editing demo</h1>

<%= render 'form' %>

<%= link_to 'Show', @demo %> |
<%= link_to 'Back', demos_path %>

app/views/demos/index.html.erb
<h1>Listing demos</h1>

<table>
  <thead>
      <th>FB ID: </th>
      <th>CREATED AT:</th>
      <th>SCRAPED AT: </th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @demos.each do |demo| %>
      <tr>
        <td><%= demo.fb_id %></td>
        <td><%= demo.created %></td>
        <td> <%= demo.created_at %></td>
        <td><%= link_to 'Show', demo %></td>
        <td><%= link_to 'Edit', edit_demo_path(demo) %></td>
        <td><%= link_to 'Destroy', demo, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Demo', new_demo_path %>

app/views/demos/new.html.erb
<h1>New demo</h1>

<%= render 'form' %>

<%= link_to 'Back', demos_path %>

app/views/demos/show.html.erb
<p id="notice"><%= notice %></p>

<h2><%= @demo.handle %></h2>
<h2><%= @demo.fb_id %></h2>
<h2><%= @demo.message %></h2>
<h2><%= @demo.picture %></h2>
<h2><%= @demo.link %></h2>
<h2><%= @demo.created_at %></h2>
<h2><%= @demo.updated %></h2>
<h2><%= @demo.shares %></h2>
<h2><%= @demo.likes %></h2>

<%= link_to 'Edit', edit_demo_path(@demo) %> |
<%= link_to 'Back', demos_path %>

app/views/layouts/_nav.html.erb
<nav class="top-bar" data-topbar>
  <ul class="title-area">
    <li class="name">
      <h1><a href="#">Treehouse</a></h1>
    </li>
  </ul>

  <section class="top-bar-section">
    <!-- Right Nav Section -->
    <ul class="right">
      <li class="active"><a href="#">Start Scraper</a></li>
      <li class="has-dropdown">
        <a href="#">Menu</a>
        <ul class="dropdown">
          <li><a href="#">First link in dropdown</a></li>
        </ul>
      </li>
    </ul>

    <!-- Left Nav Section -->
    <ul class="left">
      <li><a href="#">Help</a></li>
    </ul>
  </section>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? yield(:title) : "foundation-rails" %></title>

    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "vendor/modernizr" %>
    <%= csrf_meta_tags %>
  </head>

  <body>
    <%= render "layouts/nav" %>

    <%= yield %>
    <%= javascript_include_tag "application" %>
  </body>
</html>

app/views/scrapes/run.html.erb
run.html.erb